#!/usr/bin/env node

/**
 * Generate Genus-Based Bird Image Maps Script
 * 
 * Reads download_progress.json and generates separate TypeScript files for each genus
 * (first word of Latin name) with hardcoded require() statements for that genus only.
 * 
 * This solves the build memory issue by creating smaller, on-demand loadable image maps
 * instead of one massive file with 9,331+ require() statements.
 * 
 * Features:
 * - Groups species by genus (first word of Latin name)
 * - Creates separate TypeScript files for each genus
 * - Prefers .webp over .jpg for smaller bundle size
 * - Validates file existence before adding require() statements
 * - Generates clean TypeScript with consistent formatting
 * - Handles missing images gracefully
 * - Creates genus index for dynamic loading
 */

const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
    downloadProgressPath: path.join(__dirname, '../image_getters/download_progress.json'),
    assetsDir: path.join(__dirname, '../../assets/images/birds'),
    outputDir: path.join(__dirname, '../../services/generated/genus'),
    indexOutputPath: path.join(__dirname, '../../services/generated/genusIndex.ts'),
    relativePath: '../../../assets/images/birds' // Relative path from genus files to assets
};

// Statistics tracking
const stats = {
    totalEntries: 0,
    totalGenera: 0,
    foundWebp: 0,
    foundJpg: 0,
    notFound: 0,
    errors: 0,
    generaSpeciesCount: {}
};

/**
 * Check if a file exists
 */
function fileExists(filePath) {
    try {
        return fs.existsSync(filePath);
    } catch (error) {
        console.warn(`Error checking file existence: ${filePath}`, error.message);
        return false;
    }
}

/**
 * Extract genus (first word) from Latin name
 */
function extractGenus(latinName) {
    if (!latinName || typeof latinName !== 'string') {
        return null;
    }
    const parts = latinName.trim().split(' ');
    return parts[0] || null;
}

/**
 * Sanitize genus name for filename (remove special characters)
 */
function sanitizeGenusName(genus) {
    return genus.replace(/[^a-zA-Z0-9]/g, '_');
}

/**
 * Extract base filename from download progress entry
 */
function getBaseFilename(filename) {
    // Remove .webp or .jpg extension
    return filename.replace(/\.(webp|jpg)$/i, '');
}

/**
 * Find the best available image format for a bird
 */
function findBestImageFormat(latinName, downloadProgressFilename) {
    const baseFilename = getBaseFilename(downloadProgressFilename);
    
    // Check for .webp first (preferred)
    const webpPath = path.join(CONFIG.assetsDir, `${baseFilename}.webp`);
    const jpgPath = path.join(CONFIG.assetsDir, `${baseFilename}.jpg`);
    
    if (fileExists(webpPath)) {
        stats.foundWebp++;
        return `${baseFilename}.webp`;
    } else if (fileExists(jpgPath)) {
        stats.foundJpg++;
        return `${baseFilename}.jpg`;
    } else {
        stats.notFound++;
        console.warn(`No image found for ${latinName}: ${baseFilename}.webp or ${baseFilename}.jpg`);
        return null;
    }
}

/**
 * Generate TypeScript require statement
 */
function generateRequireStatement(filename) {
    return `require('${CONFIG.relativePath}/${filename}')`;
}

/**
 * Generate the complete TypeScript file content for a genus
 */
function generateGenusTypeScriptContent(genus, imageMap) {
    const entries = Object.entries(imageMap)
        .sort(([a], [b]) => a.localeCompare(b)) // Sort alphabetically
        .map(([filename, requireStatement]) => {
            const value = requireStatement === null ? 'null' : requireStatement;
            return `  '${filename}': ${value}`;
        })
        .join(',\n');

    const speciesCount = Object.keys(imageMap).length;
    const foundImages = Object.values(imageMap).filter(val => val !== null).length;

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Genus: ${genus}
 * This file contains image mappings for all species in the ${genus} genus.
 * Generated by generateGenusImageMaps.js
 * 
 * Generated: ${new Date().toISOString()}
 * Species in genus: ${speciesCount}
 * Images found: ${foundImages}
 * Coverage: ${Math.round((foundImages / speciesCount) * 100)}%
 */

export const ${sanitizeGenusName(genus)}ImageMap: { [key: string]: any } = {
${entries}
};

export default ${sanitizeGenusName(genus)}ImageMap;
`;
}

/**
 * Generate genus index file for dynamic loading
 */
function generateGenusIndexContent(genera) {
    const genusEntries = genera
        .sort()
        .map(genus => `  '${genus}': () => import('./genus/${sanitizeGenusName(genus)}')`)
        .join(',\n');

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Genus Index for Dynamic Image Map Loading
 * This file provides lazy loading functions for each genus image map.
 * Generated by generateGenusImageMaps.js
 * 
 * Generated: ${new Date().toISOString()}
 * Total genera: ${genera.length}
 */

export type GenusImageMapLoader = () => Promise<{ default: { [key: string]: any } }>;

export const genusLoaders: { [genus: string]: GenusImageMapLoader } = {
${genusEntries}
};

export const availableGenera = [
${genera.map(genus => `  '${genus}'`).join(',\n')}
] as const;

export type AvailableGenus = typeof availableGenera[number];

/**
 * Check if a genus has an available image map
 */
export function hasGenusMap(genus: string): boolean {
  return genus in genusLoaders;
}

/**
 * Get the sanitized filename for a genus
 */
export function getGenusFilename(genus: string): string {
  return genus.replace(/[^a-zA-Z0-9]/g, '_');
}
`;
}

/**
 * Main function to generate genus-based bird image maps
 */
async function generateGenusImageMaps() {
    console.log('🐦 Generating Genus-Based Bird Image Maps...');
    console.log(`📁 Reading from: ${CONFIG.downloadProgressPath}`);
    console.log(`📁 Assets directory: ${CONFIG.assetsDir}`);
    console.log(`📁 Output directory: ${CONFIG.outputDir}`);
    
    try {
        // Read download progress
        if (!fileExists(CONFIG.downloadProgressPath)) {
            throw new Error(`Download progress file not found: ${CONFIG.downloadProgressPath}`);
        }
        
        const downloadProgressData = fs.readFileSync(CONFIG.downloadProgressPath, 'utf8');
        const downloadProgress = JSON.parse(downloadProgressData);
        
        stats.totalEntries = Object.keys(downloadProgress).length;
        console.log(`📊 Found ${stats.totalEntries} entries in download progress`);
        
        // Check assets directory
        if (!fileExists(CONFIG.assetsDir)) {
            throw new Error(`Assets directory not found: ${CONFIG.assetsDir}`);
        }
        
        // Ensure output directory exists
        if (!fileExists(CONFIG.outputDir)) {
            fs.mkdirSync(CONFIG.outputDir, { recursive: true });
        }
        
        // Group species by genus
        const genusGroups = {};
        
        for (const [latinName, filename] of Object.entries(downloadProgress)) {
            const genus = extractGenus(latinName);
            if (!genus) {
                stats.errors++;
                console.warn(`Could not extract genus from: ${latinName}`);
                continue;
            }
            
            if (!genusGroups[genus]) {
                genusGroups[genus] = {};
                stats.generaSpeciesCount[genus] = 0;
            }
            
            stats.generaSpeciesCount[genus]++;
            
            if (!filename) {
                stats.notFound++;
                // Add null entry for missing filename
                genusGroups[genus][`${latinName.toLowerCase().replace(/\s+/g, '_')}.webp`] = null;
                continue;
            }
            
            try {
                const bestFormat = findBestImageFormat(latinName, filename);
                if (bestFormat) {
                    genusGroups[genus][bestFormat] = generateRequireStatement(bestFormat);
                } else {
                    // Add null entry for missing image files
                    const baseFilename = getBaseFilename(filename);
                    genusGroups[genus][`${baseFilename}.webp`] = null;
                }
            } catch (error) {
                stats.errors++;
                console.error(`Error processing ${latinName}:`, error.message);
                // Add null entry for errors
                const baseFilename = filename ? getBaseFilename(filename) : latinName.toLowerCase().replace(/\s+/g, '_');
                genusGroups[genus][`${baseFilename}.webp`] = null;
            }
        }
        
        stats.totalGenera = Object.keys(genusGroups).length;
        console.log(`📊 Found ${stats.totalGenera} unique genera`);
        
        // Generate individual genus files
        console.log('🔄 Generating genus files...');
        for (const [genus, imageMap] of Object.entries(genusGroups)) {
            const sanitizedGenus = sanitizeGenusName(genus);
            const genusFilePath = path.join(CONFIG.outputDir, `${sanitizedGenus}.ts`);
            const genusContent = generateGenusTypeScriptContent(genus, imageMap);
            
            fs.writeFileSync(genusFilePath, genusContent, 'utf8');
            console.log(`✅ Generated: ${sanitizedGenus}.ts (${Object.keys(imageMap).length} species)`);
        }
        
        // Generate genus index file
        console.log('🔄 Generating genus index...');
        const genera = Object.keys(genusGroups);
        const indexContent = generateGenusIndexContent(genera);
        fs.writeFileSync(CONFIG.indexOutputPath, indexContent, 'utf8');
        console.log(`✅ Generated: genusIndex.ts`);
        
        // Print detailed statistics
        console.log('\\n📊 Generation Statistics:');
        console.log(`✅ Total entries processed: ${stats.totalEntries}`);
        console.log(`🗂️  Total genera: ${stats.totalGenera}`);
        console.log(`🖼️  WebP images found: ${stats.foundWebp}`);
        console.log(`🖼️  JPG images found: ${stats.foundJpg}`);
        console.log(`❌ Images not found: ${stats.notFound}`);
        console.log(`⚠️  Errors: ${stats.errors}`);
        
        // Show top 10 genera by species count
        console.log('\\n📈 Top 10 Genera by Species Count:');
        const sortedGenera = Object.entries(stats.generaSpeciesCount)
            .sort(([,a], [,b]) => b - a)
            .slice(0, 10);
        
        sortedGenera.forEach(([genus, count], index) => {
            console.log(`${String(index + 1).padStart(2)}. ${genus}: ${count} species`);
        });
        
        const totalMappedImages = stats.foundWebp + stats.foundJpg;
        const coveragePercentage = Math.round((totalMappedImages / stats.totalEntries) * 100);
        console.log(`\\n📈 Overall Coverage: ${coveragePercentage}%`);
        
        console.log(`\\n✅ Successfully generated ${stats.totalGenera} genus files!`);
        console.log(`📁 Output directory: ${CONFIG.outputDir}`);
        console.log(`📦 Ready for dynamic loading!`);
        
    } catch (error) {
        console.error('❌ Error generating genus image maps:', error.message);
        process.exit(1);
    }
}

// Run the script if called directly
if (require.main === module) {
    generateGenusImageMaps().catch(error => {
        console.error('❌ Unhandled error:', error);
        process.exit(1);
    });
}

module.exports = { generateGenusImageMaps };